apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-group34
  namespace: nju34
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cloud-native-34
  template:
    metadata:
      labels:
        app: cloud-native-34
    spec:
      containers:
        - name: group34-containers
          image: harbor.edu.cn/nju34/34_images:VERSION
          resources:
            requests:
              memory: 50Mi
              cpu: 50m
      imagePullSecrets:
        - name: nju34
