apiVersion: v1
kind: Service
metadata:
  name: cloud-native-34-svc
  namespace: nju34
  labels:
    app : cloud-native-34
spec:
  type: NodePort
  selector:
    app: cloud-native-34
  ports:
    - nodePort: 30034
      port: 8888
      targetPort: 8080
      protocol: TCP
      name: metrics