apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: project-group34-monitor
  namespace: monitoring
  labels:
    app: cloud-native-34
spec:
  namespaceSelector:
    matchNames:
      - nju34
  selector:
    matchLabels:
      app: cloud-native-34
  endpoints:
    - port: http
      interval: 15s
      path: /actuator/prometheus
      scheme: 'http'